version: '3'
services:
  postgres:
    image: postgres:10.4
    environment:
      - POSTGRES_USER=sample_user
      - POSTGRES_PASSWORD=sample_user
      - POSTGRES_DB=sample_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432